<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="jvmti.xsl"?>
<!--
  ~ StarshipOS Copyright (c) 2002-2025. R.A. James
  -->

<!DOCTYPE specification [
   <!ELEMENT specification (title, intro*, functionsection, errorsection,
                            eventsection, datasection, issuessection, changehistory)>
   <!ATTLIST specification label CDATA #REQUIRED>

   <!ELEMENT title (#PCDATA|jvmti|tm)*>
   <!ATTLIST title subtitle CDATA #REQUIRED>

   <!ELEMENT intro ANY>
   <!ATTLIST intro id CDATA #IMPLIED
                   label CDATA "">

   <!ELEMENT functionsection (intro*, category*)>
   <!ATTLIST functionsection label CDATA #REQUIRED>

   <!ELEMENT category ((intro|typedef|uniontypedef|capabilitiestypedef)*,
                          (function|callback|elide)*)>
   <!ATTLIST category id CDATA #REQUIRED
                      label CDATA #REQUIRED>

   <!ELEMENT function (synopsis, typedef*, description?, origin,
                         (capabilities|eventcapabilities),
                         parameters, errors)>
   <!ATTLIST function id CDATA #REQUIRED
                      num CDATA #REQUIRED
                      phase (onload|onloadOnly|start|live|any) #IMPLIED
                      callbacksafe (safe|unsafe) #IMPLIED
                      impl CDATA #IMPLIED
                      hide CDATA #IMPLIED
                      jkernel (yes|no) #IMPLIED
                      since CDATA "1.0">

   <!ELEMENT callback ((jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|jthreadGroup|jobject|
                        jvalue|enum|jint|jlong|jfloat|jdouble|jlocation|jboolean|char|uchar|size_t|void),
                        synopsis, description?, parameters)>
   <!ATTLIST callback id CDATA #REQUIRED
                      since CDATA "1.0">

   <!ELEMENT synopsis (#PCDATA|jvmti)*>

   <!ELEMENT typedef (description?, field*)>
   <!ATTLIST typedef id CDATA #REQUIRED
                     label CDATA #REQUIRED
                     since CDATA "1.0">

   <!ELEMENT uniontypedef (description?, field*)>
   <!ATTLIST uniontypedef id CDATA #REQUIRED
                     label CDATA #REQUIRED
                     since CDATA "1.0">

   <!ELEMENT field ((jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|jthreadGroup|jobject|
                     jvalue|enum|jint|jlong|jfloat|jdouble|jlocation|jboolean|char|uchar|size_t|void|allocfieldbuf|inptr|inbuf|outbuf|vmbuf|ptrtype|struct),
                    description)>
   <!ATTLIST field id CDATA #REQUIRED>

   <!ELEMENT capabilitiestypedef (description?, capabilityfield*)>
   <!ATTLIST capabilitiestypedef id CDATA #REQUIRED
                     label CDATA #REQUIRED>

   <!ELEMENT capabilityfield (description)>
   <!ATTLIST capabilityfield id CDATA #REQUIRED
                   disp1 CDATA ""
                   disp2 CDATA ""
                   since CDATA "1.0">

   <!ELEMENT description ANY>

   <!ELEMENT capabilities (required*, capability*)>

   <!ELEMENT eventcapabilities EMPTY>

   <!ELEMENT required ANY>
   <!ATTLIST required id CDATA #REQUIRED>

   <!ELEMENT capability ANY>
   <!ATTLIST capability id CDATA #REQUIRED>

   <!ELEMENT parameters (param*)>

   <!ELEMENT param ((jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|jthreadGroup|jobject|
                     jvalue|enum|jint|jlong|jfloat|jdouble|jlocation|jboolean|char|uchar|size_t|void|varargs|struct|ptrtype|
                     outptr|allocbuf|allocallocbuf|inptr|inbuf|outbuf|vmbuf|agentbuf),
                    description)>
   <!ATTLIST param id CDATA #REQUIRED>

   <!ELEMENT jmethodID EMPTY>
   <!ATTLIST jmethodID class  CDATA #IMPLIED
                       native CDATA #IMPLIED>

   <!ELEMENT jfieldID EMPTY>
   <!ATTLIST jfieldID class CDATA #IMPLIED>

   <!ELEMENT jclass EMPTY>
   <!ATTLIST jclass method CDATA #IMPLIED
                    field  CDATA #IMPLIED>

   <!ELEMENT jframeID EMPTY>
   <!ATTLIST jframeID thread CDATA #IMPLIED>

   <!ELEMENT jrawMonitorID EMPTY>

   <!ELEMENT jthread EMPTY>
   <!ATTLIST jthread started CDATA #IMPLIED
                     null CDATA #IMPLIED
                     frame CDATA #IMPLIED
                     impl CDATA #IMPLIED>

   <!ELEMENT varargs EMPTY>

   <!ELEMENT jthreadGroup EMPTY>
   <!ELEMENT jobject EMPTY>
   <!ATTLIST jobject frame CDATA #IMPLIED>

   <!ELEMENT jvalue EMPTY>
   <!ELEMENT jchar EMPTY>
   <!ELEMENT jint EMPTY>
   <!ATTLIST jint min CDATA #IMPLIED>
   <!ELEMENT jlong EMPTY>
   <!ELEMENT jfloat EMPTY>
   <!ELEMENT jdouble EMPTY>
   <!ELEMENT jlocation EMPTY>
   <!ELEMENT jboolean EMPTY>
   <!ELEMENT char EMPTY>
   <!ELEMENT uchar EMPTY>
   <!ELEMENT size_t EMPTY>
   <!ELEMENT void EMPTY>
   <!ELEMENT enum (#PCDATA)*>
   <!ELEMENT struct (#PCDATA)*>

   <!ELEMENT nullok ANY>

   <!ELEMENT ptrtype     ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue), nullok?)>

   <!ELEMENT outptr     ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jchar|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void), nullok?)>
   <!ATTLIST outptr impl CDATA #IMPLIED>

   <!ELEMENT allocbuf   ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void), nullok?)>
   <!ATTLIST allocbuf incount CDATA #IMPLIED
                      outcount CDATA #IMPLIED>

   <!ELEMENT allocallocbuf   ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void), nullok?)>
   <!ATTLIST allocallocbuf incount CDATA #IMPLIED
                      outcount CDATA #IMPLIED>

   <!ELEMENT inptr      (struct, nullok?)>

   <!ELEMENT inbuf      ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void), nullok?)>
   <!ATTLIST inbuf    incount CDATA #IMPLIED>

   <!ELEMENT outbuf     ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void|outbuf), nullok?)>
   <!ATTLIST outbuf   incount CDATA #IMPLIED
                      outcount CDATA #IMPLIED>

   <!ELEMENT vmbuf      ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jchar|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void), nullok?)>
   <!ATTLIST vmbuf    incount CDATA #IMPLIED
                      outcount CDATA #IMPLIED>

   <!ELEMENT agentbuf   ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void), nullok?)>
   <!ATTLIST agentbuf incount CDATA #IMPLIED
                      outcount CDATA #IMPLIED>

   <!ELEMENT allocfieldbuf   ((struct|jmethodID|jfieldID|jframeID|jrawMonitorID|jclass|jthread|
                                   jthreadGroup|jobject|jvalue|enum|jint|jlong|jfloat|jdouble|
                                   jlocation|jboolean|char|uchar|size_t|void))>
   <!ATTLIST allocfieldbuf outcount CDATA #IMPLIED>

   <!ELEMENT errors (error*)>

   <!ELEMENT error ANY>
   <!ATTLIST error id CDATA #REQUIRED>

   <!ELEMENT errorsection (intro*, errorcategory*)>
   <!ATTLIST errorsection label CDATA #REQUIRED>

   <!ELEMENT errorcategory (intro*, errorid*)>
   <!ATTLIST errorcategory id CDATA #REQUIRED
                           label CDATA #REQUIRED>

   <!ELEMENT errorid ANY>
   <!ATTLIST errorid id CDATA #REQUIRED
                     num CDATA #REQUIRED>

   <!ELEMENT datasection (intro*, basetypes*)>

   <!ELEMENT basetypes (intro*, basetype*)>
   <!ATTLIST basetypes id CDATA #REQUIRED
                       label CDATA #REQUIRED>

   <!ELEMENT basetype (definition?,description)>
   <!ATTLIST basetype id CDATA #REQUIRED
                      name CDATA #IMPLIED>

   <!ELEMENT definition (#PCDATA|jvmti)*>

   <!ELEMENT eventsection (intro*, (event|elide)*)>
   <!ATTLIST eventsection label CDATA #REQUIRED>

   <!ELEMENT event (description, origin, typedef*, capabilities, parameters)>
   <!ATTLIST event id CDATA #REQUIRED
                   label CDATA #REQUIRED
                   const CDATA #REQUIRED
                   num CDATA #REQUIRED
                   phase (onload|start|live|any) #IMPLIED
                   filtered (thread|global) #IMPLIED
                   since CDATA "1.0">

   <!ELEMENT issuessection (intro*)>
   <!ATTLIST issuessection label CDATA #REQUIRED>

   <!ELEMENT changehistory (intro*, change*)>
   <!ATTLIST changehistory update CDATA #REQUIRED
                           id CDATA #REQUIRED>

   <!ELEMENT change ANY>
   <!ATTLIST change date CDATA #REQUIRED
                    version CDATA #IMPLIED>

   <!ELEMENT functionlink (#PCDATA|jvmti|code|i|b)*>
   <!ATTLIST functionlink id CDATA #REQUIRED>

   <!ELEMENT datalink (#PCDATA|jvmti|code|i|b)*>
   <!ATTLIST datalink id CDATA #REQUIRED>

   <!ELEMENT typelink (#PCDATA|jvmti|code|i|b)*>
   <!ATTLIST typelink id CDATA #REQUIRED>

   <!ELEMENT fieldlink (#PCDATA|jvmti|code|i|b)*>
   <!ATTLIST fieldlink id CDATA #REQUIRED
                       struct CDATA #REQUIRED>

   <!ELEMENT paramlink (#PCDATA|jvmti|code|i|b)*>
   <!ATTLIST paramlink id CDATA #REQUIRED>

   <!ELEMENT eventlink (#PCDATA|jvmti|code|i|b)*>
   <!ATTLIST eventlink id CDATA #REQUIRED>

   <!ELEMENT errorlink (#PCDATA|jvmti|code|i|b|tm)*>
   <!ATTLIST errorlink id CDATA #REQUIRED>

   <!ELEMENT externallink (#PCDATA|jvmti|code|i|b|tm)*>
   <!ATTLIST externallink id CDATA #REQUIRED>

   <!ELEMENT vmspec EMPTY>
   <!ATTLIST vmspec chapter CDATA #IMPLIED>

   <!ELEMENT internallink (#PCDATA|jvmti|code|i|b)*>
   <!ATTLIST internallink id CDATA #REQUIRED>

   <!ELEMENT functionphaselist EMPTY>
   <!ATTLIST functionphaselist phase (onload|onloadOnly|start|live|any) #REQUIRED>

   <!ELEMENT eventphaselist EMPTY>
   <!ATTLIST eventphaselist phase (onload|start|live|any) #REQUIRED>

   <!ELEMENT issue ANY>

   <!ELEMENT rationale ANY>

   <!ELEMENT todo ANY>

   <!ELEMENT origin (#PCDATA)*>

   <!ELEMENT elide (intro|function|callback|event)*>
   <!ATTLIST elide why CDATA #IMPLIED>

   <!ELEMENT constants (constant*)>
   <!ATTLIST constants id CDATA #REQUIRED
                       label CDATA #REQUIRED
                       kind (enum|bits|const) #REQUIRED
                       since CDATA "1.0">

   <!ELEMENT constant ANY>
   <!ATTLIST constant id CDATA #REQUIRED
                      num CDATA #REQUIRED>

   <!ELEMENT tm (#PCDATA)>

   <!ELEMENT i (#PCDATA|jvmti|tm)*>

   <!ELEMENT b (#PCDATA|jvmti|code)*>

   <!ELEMENT code (#PCDATA|space)*>

   <!ELEMENT pre ANY>

   <!ELEMENT space EMPTY>

   <!ELEMENT jvmti EMPTY>

   <!ELEMENT example (#PCDATA|i)*>

   <!ELEMENT br EMPTY>

   <!ELEMENT p EMPTY>

   <!ELEMENT blockquote ANY>

   <!ELEMENT dl  (dt|dd)+>

   <!ELEMENT dd  ANY>

   <!ELEMENT dt  (#PCDATA|jvmti|code|i|b)*>

   <!ELEMENT table  (tr)+>

   <!ELEMENT tr  (td|th)*>
   <!ATTLIST tr class CDATA #IMPLIED>

   <!ELEMENT td  ANY>
   <!ATTLIST td class CDATA #IMPLIED>

   <!ELEMENT th  ANY>
   <!ATTLIST th class CDATA #IMPLIED
                scope (col|row) #IMPLIED>

   <!ELEMENT ul  (li)+>
   <!ATTLIST ul type (disc|circle|square) "disc">

   <!ELEMENT li  ANY>
 ]>

<specification label="JVM(TM) Tool Interface">
  <title subtitle="Version">
    <tm>JVM</tm> Tool Interface
  </title>

  <intro id="whatIs" label="What is the JVM Tool Interface?">
    The <tm>JVM</tm> Tool Interface (<jvmti/>)
    is a programming interface used by development and monitoring tools.
    It provides both a way to inspect the state and
    to control the execution of applications running in the
    <tm>Java</tm> virtual machine (VM).
    <p/>
    <jvmti/> is intended to provide a VM interface for the full breadth of tools
    that need access to VM state, including but not limited to: profiling,
    debugging, monitoring, thread analysis, and coverage analysis tools.
    <p/>
    <jvmti/> may not be available in all implementations of the <tm>Java</tm> virtual
    machine.
    <p/>
    <jvmti/> is a two-way interface.
    A client of <jvmti/>, hereafter called an <i>agent</i>,
    can be notified of
    interesting occurrences through <internallink id="EventSection">events</internallink>.
    <jvmti/>
    can query and control the application through many
    <internallink id="FunctionSection">functions</internallink>,
    either in response to events or
    independent of them.
    <p/>
    Agents run in the same process with and communicate directly with
    the virtual machine executing
    the application being examined.  This communication is
    through a native interface (<jvmti/>). The native in-process interface allows
    maximal control with minimal intrusion on the part of a tool.
    Typically, agents are relatively compact. They can be controlled
    by a separate process which implements the bulk of a tool's
    function without interfering with the target application's normal execution.
  </intro>

  <intro id="architecture" label="Architecture">
    Tools can be written directly to <jvmti/> or indirectly
    through higher level interfaces.
    The Java Platform Debugger Architecture includes <jvmti/>, but also
    contains higher-level, out-of-process debugger interfaces. The higher-level
    interfaces are more appropriate than <jvmti/> for many tools.
    For more information on the Java Platform Debugger Architecture,
    see the
    <externallink id="jpda/architecture.html">Java
      Platform Debugger Architecture website</externallink>.
  </intro>

  <intro id="writingAgents" label="Writing Agents">
    Agents can be written in any native language that supports C
    language calling conventions and C or C++
    definitions.
    <p/>
    The function, event, data type, and constant definitions needed for
    using <jvmti/> are defined in the include file <code>jvmti.h</code>.
    To use these definitions add the <tm>J2SE</tm> include directory
    to your include path and add
    <example>
#include &lt;jvmti.h&gt;
    </example>
    to your source code.
  </intro>

  <intro id="deployingAgents" label="Deploying Agents">
    An agent is deployed in a platform specific manner but is typically the
    platform equivalent of a dynamic library. On the <tm>Windows</tm> operating
    system, for example, an agent library is a "Dynamic Linked Library" (DLL).
    On <tm>Linux</tm> Operating Environment, an agent library is a shared object
    (<code>.so</code> file).
    <p/>

    An agent may be started at VM startup by specifying the agent library
    name using a <internallink id="starting">command line option</internallink>.
    Some implementations may support a mechanism to <internallink id="onattach">
    start agents</internallink> in the live <functionlink id="GetPhase">phase</functionlink>.
    The details of how this is initiated are implementation specific.
  </intro>

    <intro id="entryPoint" label="Statically Linked Agents (since version 1.2.3)">

      A native JVMTI Agent may be <i>statically linked</i> with the VM.
      The manner in which the library and VM image are combined is
      implementation-dependent.
      An agent L whose image has been combined with the VM is defined as
      <i>statically linked</i> if and only if the agent exports a function
      called Agent_OnLoad_L.
<p/>
      If a <i>statically linked</i> agent L exports a function called
      Agent_OnLoad_L and a function called Agent_OnLoad, the Agent_OnLoad
      function will be ignored.
      If an agent L is <i>statically linked</i>, an Agent_OnLoad_L
      function will be invoked with the same arguments and expected return
      value as specified for the Agent_OnLoad function.
      An agent L that is <i>statically linked</i> will prohibit an agent of
      the same name from being loaded dynamically.
<p/>
      The VM will invoke the Agent_OnUnload_L function of the agent, if such
      a function is exported, at the same point during VM execution as it would
      have called the dynamic entry point Agent_OnUnLoad. A statically loaded
      agent cannot be unloaded. The Agent_OnUnload_L function will still be
      called to do any other agent shutdown related tasks.
      If a <i>statically linked</i> agent L exports a function called
      Agent_OnUnLoad_L and a function called Agent_OnUnLoad, the Agent_OnUnLoad
      function will be ignored.
<p/>
      If an agent L is <i>statically linked</i>, an Agent_OnAttach_L function
      will be invoked with the same arguments and expected return value as
      specified for the Agent_OnAttach function.
      If a <i>statically linked</i> agent L exports a function called
      Agent_OnAttach_L and a function called Agent_OnAttach, the Agent_OnAttach
      function will be ignored.
</intro>

  <intro id="starting" label="Agent Command Line Options">
    The term "command-line option" is used below to
    mean options supplied in the <code>JavaVMInitArgs</code> argument
    to the <code>JNI_CreateJavaVM</code> function of the JNI
    Invocation API.
    <p/>
    One of the two following
    command-line options is used on VM startup to
    properly load and run agents.
    These arguments identify the library containing
    the agent as well as an options
    string to be passed in at startup.
    <dl>
      <dt><code>-agentlib:</code><i>&lt;agent-lib-name&gt;</i><code>=</code><i>&lt;options&gt;</i></dt>
      <dd>
        The name following <code>-agentlib:</code> is the name of the
        library to load.  Lookup of the library, both its full name and location,
        proceeds in a platform-specific manner.
        Typically, the <i>&lt;agent-lib-name&gt;</i> is expanded to an
        operating system specific file name.
        The <i>&lt;options&gt;</i> will be passed to the agent on start-up.
        For example, if the option
        <code>-agentlib:foo=opt1,opt2</code> is specified, the VM will attempt to
        load the shared library <code>foo.dll</code> from the system <code>PATH</code>
        under <tm>Windows</tm> or <code>libfoo.so</code> from the
        <code>LD_LIBRARY_PATH</code> under <tm>Linux</tm>.
        If the agent library is statically linked into the executable
        then no actual loading takes place.
    <p/>
      </dd>
      <dt><code>-agentpath:</code><i>&lt;path-to-agent&gt;</i><code>=</code><i>&lt;options&gt;</i></dt>
      <dd>
        The path following <code>-agentpath:</code> is the absolute path from which
        to load the library.
        No library name expansion will occur.
        The <i>&lt;options&gt;</i> will be passed to the agent on start-up.
        For example, if the option
        <code>-agentpath:c:\myLibs\foo.dll=opt1,opt2</code> is specified, the VM will attempt to
        load the shared library <code>c:\myLibs\foo.dll</code>. If the agent
        library is statically linked into the executable
        then no actual loading takes place.
    <p/>
      </dd>
    </dl>
    For a dynamic shared library agent, the start-up routine
    <internallink id="onload"><code>Agent_OnLoad</code></internallink>
    in the library will be invoked. If the agent library is statically linked
    into the executable then the system will attempt to invoke the
    <code>Agent_OnLoad_&lt;agent-lib-name&gt;</code> entry point where
    &lt;agent-lib-name&gt; is the basename of the
    agent. In the above example <code>-agentpath:c:\myLibs\foo.dll=opt1,opt2</code>,
    the system will attempt to find and call the <code>Agent_OnLoad_foo</code> start-up routine.
    <p/>
    Libraries loaded with <code>-agentlib:</code> or <code>-agentpath:</code>
    will be searched for JNI native method implementations to facilitate the
    use of Java programming language code in tools, as is needed for
    <internallink id="bci">bytecode instrumentation</internallink>.
    <p/>
    The agent libraries will be searched after all other libraries have been
    searched (agents wishing to override or intercept the native method
    implementations of non-agent methods can use the
    <eventlink id="NativeMethodBind">NativeMethodBind event</eventlink>).
    <p/>
    These switches do the above and nothing more - they do not change the
    state of the VM or <jvmti/>.  No command line options are needed
    to enable <jvmti/>
    or aspects of <jvmti/>, this is handled programmatically
    by the use of
    <internallink id="capability">capabilities</internallink>.
  </intro>

  <intro id="startup" label="Agent Start-Up">
    The VM starts each agent by invoking a start-up function.
    If the agent is started in the <code>OnLoad</code>
    <functionlink id="GetPhase">phase</functionlink> the function
    <internallink id="onload"><code>Agent_OnLoad</code></internallink>
    or <internallink id="onload"><code>Agent_OnLoad_L</code></internallink>
    for statically linked agents will be invoked.
    If the agent is started in the live
    <functionlink id="GetPhase">phase</functionlink> the function
    <internallink id="onattach"><code>Agent_OnAttach</code></internallink>
    or <internallink id="onattach"><code>Agent_OnAttach_L</code></internallink>
    for statically linked agents will be invoked.
    Exactly one call to a start-up function is made per agent.
  </intro>

  <intro id="onload" label="Agent Start-Up (OnLoad phase)">
    If an agent is started during the <code>OnLoad</code> phase then its
    agent library must export a start-up function with the following prototype:
    <example>
JNIEXPORT jint JNICALL
Agent_OnLoad(JavaVM *vm, char *options, void *reserved)</example>
    Or for a statically linked agent named 'L':
    <example>
JNIEXPORT jint JNICALL
Agent_OnLoad_L(JavaVM *vm, char *options, void *reserved)</example>

    The VM will start the agent by calling this function.
    It will be called early enough in VM initialization that:
    <ul>
      <li><functionlink id="SetSystemProperty">system properties</functionlink>
        may be set before they have been used in the start-up of the VM</li>
      <li>the full set of
        <internallink id="capability">capabilities</internallink>
        is still available (note that capabilities that configure the VM
        may only be available at this time--see the
        <internallink id="capability">Capability function section</internallink>)</li>
      <li>no bytecodes have executed</li>
      <li>no classes have been loaded</li>
      <li>no objects have been created</li>
    </ul>
    <p/>
    The VM will call the <code>Agent_OnLoad</code> or
    <code>Agent_OnLoad_&lt;agent-lib-name&gt;</code> function with
    <i>&lt;options&gt;</i> as the second argument -
    that is, using the command-line option examples,
    <code>"opt1,opt2"</code> will be passed to the <code>char *options</code>
    argument of <code>Agent_OnLoad</code>.
    The <code>options</code> argument is encoded as a
    <internallink id="mUTF">modified UTF-8</internallink> string.
    If <i>=&lt;options&gt;</i> is not specified,
    a zero length string is passed to <code>options</code>.
    The lifespan of the <code>options</code> string is the
    <code>Agent_OnLoad</code> or <code>Agent_OnLoad_&lt;agent-lib-name&gt;</code>
    call.  If needed beyond this time the string or parts of the string must
    be copied.
    The period between when <code>Agent_OnLoad</code> is called and when it
    returns is called the <i>OnLoad phase</i>.
    Since the VM is not initialized during the OnLoad
    <functionlink id="GetPhase">phase</functionlink>,
    the set of allowed operations
    inside <code>Agent_OnLoad</code> is restricted (see the function descriptions for the
    functionality available at this time).
    The agent can safely process the options and set
    event callbacks with <functionlink id="SetEventCallbacks"></functionlink>. Once
    the VM initialization event is received
    (that is, the <eventlink id="VMInit">VMInit</eventlink>
    callback is invoked), the agent
    can complete its initialization.
    <rationale>
      Early startup is required so that agents can set the desired capabilities,
      many of which must be set before the VM is initialized.
      In JVMDI, the -Xdebug command-line option provided
      very coarse-grain control of capabilities.
      JVMPI implementations use various tricks to provide a single "JVMPI on" switch.
      No reasonable command-line
      option could provide the fine-grain of control required to balance needed capabilities vs
      performance impact.
      Early startup is also needed so that agents can control the execution
      environment - modifying the file system and system properties to install
      their functionality.
    </rationale>
    <p/>
    The return value from <code>Agent_OnLoad</code> or
    <code>Agent_OnLoad_&lt;agent-lib-name&gt;</code> is used to indicate an error.
    Any value other than zero indicates an error and causes termination of the VM.
  </intro>

  <intro id="onattach" label="Agent Start-Up (Live phase)">
    A VM may support a mechanism that allows agents to be started in the VM during the live
    <functionlink id="GetPhase">phase</functionlink>. The details of how this is supported,
    are implementation specific. For example, a tool may use some platform specific mechanism,
    or implementation specific API, to attach to the running VM, and request it start a given
    agent.
    <p/>
    The VM prints a warning on the standard error stream for each agent that it attempts
    to start in the live phase. If an agent was previously started (in the <code>OnLoad</code>
    phase or in the live phase), then it is implementation specific as to whether a
    warning is printed when attempting to start the same agent a second or subsequent time.
    Warnings can be disabled by means of an implementation-specific command line option.
    <p/>
    <b>Implementation Note:</b> For the HotSpot VM, the VM option
    <code>-XX:+EnableDynamicAgentLoading</code> is used to opt-in to allow dynamic loading
    of agents in the live phase. This option suppresses the warning to standard error when
    starting an agent in the live phase.
    <p/>
    If an agent is started during the live phase then its agent library
    must export a start-up function
    with the following prototype:
    <example>
JNIEXPORT jint JNICALL
Agent_OnAttach(JavaVM* vm, char *options, void *reserved)</example>
Or for a statically linked agent named 'L':
    <example>
JNIEXPORT jint JNICALL
Agent_OnAttach_L(JavaVM* vm, char *options, void *reserved)</example>

    <p/>
    The VM will start the agent by calling this function.
    It will be called in the context of a thread
    that is attached to the VM. The first argument <i>&lt;vm&gt;</i> is the Java VM.
    The <i>&lt;options&gt;</i> argument is the startup options provided to the agent.
    <i>&lt;options&gt;</i> is encoded as a <internallink id="mUTF">modified UTF-8
    </internallink> string.
    If startup options were not provided, a zero length string is passed to
    <code>options</code>. The lifespan of the <code>options</code> string is the
    <code>Agent_OnAttach</code> or <code>Agent_OnAttach_&lt;agent-lib-name&gt;</code> call.
    If needed beyond this time the string or parts of the string must be copied.
    <p/>
    Note that some <internallink id="capability">capabilities</internallink>
    may not be available in the live phase.
    <p/>
    The <code>Agent_OnAttach</code> or <code>Agent_OnAttach_&lt;agent-lib-name
    &gt;</code> function initializes the agent and returns a value
    to the VM to indicate if an error occurred. Any value other than zero indicates an error.
    An error does not cause the VM to terminate. Instead the VM ignores the error, or takes
    some implementation specific action -- for example it might print an error to standard error,
    or record the error in a system log.
  </intro>

  <intro id="onunload" label="Agent Shutdown">
    The library may optionally export a
    shutdown function with the following prototype:
    <example>
JNIEXPORT void JNICALL
Agent_OnUnload(JavaVM *vm)</example>
    Or for a statically linked agent named 'L':
    <example>
JNIEXPORT void JNICALL
Agent_OnUnload_L(JavaVM *vm)</example>

    This function will be called by the VM when the library is about to be unloaded.
    The library will be unloaded (unless it is statically linked into the
    executable) and this function will be called if some platform specific
    mechanism causes the unload (an unload mechanism is not specified in this document)
    or the library is (in effect) unloaded by the termination of the VM.
    VM termination includes normal termination and VM failure, including start-up failure,
    but not, of course, uncontrolled shutdown. An implementation may also
    choose to not call this function if the <code>Agent_OnAttach</code>/
    <code>Agent_OnAttach_L</code> function reported an error (returned a non-zero value).
    Note the distinction between this function and the
    <eventlink id="VMDeath">VM Death event</eventlink>: for the VM Death event
    to be sent, the VM must have run at least to the point of initialization and a valid