=== RobJames44035/StarshipOS/openjdk23/jdk/test/jaxp/javax/xml/jaxp/unittest/transform/NCAA_Conference_Schedule_XML.dtd
<!--
  - StarshipOS Copyright (c) 2025. R.A. James
  -->

<!ELEMENT message  (XML_File_ID , heading , category , sport , Title , Conference_Schedule , time_stamp )>

<!ELEMENT XML_File_ID  (#PCDATA )>

<!ELEMENT heading  (#PCDATA )>

<!ELEMENT category  (#PCDATA )>

<!ELEMENT sport  (#PCDATA )>

<!ELEMENT Title  (#PCDATA )>

<!ELEMENT Conference_Schedule  (Team+ )>

<!ELEMENT Team  (Listing+ )>
<!ATTLIST Team  fullname CDATA  #REQUIRED >
<!ELEMENT Listing  (#PCDATA )>

<!ELEMENT time_stamp  (#PCDATA )>

=== RobJames44035/StarshipOS/openjdk23/jdk/test/jaxp/javax/xml/jaxp/unittest/transform/5368141.xml
<?xml version="1.0" standalone="no" ?>
<!--
  ~ StarshipOS Copyright (c) 2025. R.A. James
  -->

<!DOCTYPE message PUBLIC "-//TSN//DTD Statistics 1.0/EN" "NCAA_Conference_Schedule_XML.dtd">
<message>
<XML_File_ID>5368141</XML_File_ID>
<heading>AEX%06ATLANTICSUN-SKED</heading>
<category>Statistics</category>
<sport>CBASK</sport>
<Title>2006-2007 Atlantic Sun Basketball Schedule/Results</Title>
<Conference_Schedule>
<Team fullname="Belmont Bruins">
<Listing>Nov 13-L at  UNC-Wilmington, 83-88</Listing>
<Listing>Nov 14-W vs. Fordham, 56-49</Listing>
<Listing>Nov 18-W at  IUPUI, 67-61</Listing>
<Listing>Nov 20-W vs. Fisk, 83-54</Listing>
<Listing>Nov 27-L at  Middle Tennessee, 57-64</Listing>
<Listing>Nov 30-W vs. North Florida, 87-32</Listing>
<Listing>Dec  2-W vs. Jacksonville, 76-62</Listing>
<Listing>Dec  4-W vs. IUPUI, 76-66</Listing>
<Listing>Dec 13-W at  Ark-Little Rock, 72-57</Listing>
<Listing>Dec 17-L at  Illinois, 51-77</Listing>
<Listing>Dec 19-L at  Michigan State, 58-67</Listing>
<Listing>Dec 28-W at  Rice, 87-85</Listing>
<Listing>Dec 29-L at  St Marys-CA, 60-71</Listing>
<Listing>Jan  2-W at  East Tenn St, 75-74 OT</Listing>
<Listing>Jan  4-W at  Kennesaw St, 63-45</Listing>
<Listing>Jan  7-W vs. Mercer, 72-47</Listing>
<Listing>Jan  9-W vs. Stetson, 73-71</Listing>
<Listing>Jan 12-L vs. Lipscomb, 50-55</Listing>
<Listing>Jan 18- at  Campbell, 7:00 PM</Listing>
<Listing>Jan 20- at  Gardner-Webb, 6:00 PM</Listing>
<Listing>Jan 25- vs. East Tenn St, 7:00 PM</Listing>
<Listing>Jan 27- vs. Kennesaw St, 7:00 PM</Listing>
<Listing>Feb  1- at  Stetson, 6:00 PM</Listing>
<Listing>Feb  3- at  Mercer, 6:00 PM</Listing>
<Listing>Feb  9- at  Lipscomb, 6:30 PM</Listing>
<Listing>Feb 15- vs. Gardner-Webb, 7:00 PM</Listing>
<Listing>Feb 17- vs. Campbell, 7:30 PM</Listing>
<Listing>Feb 22- at  Jacksonville, 6:00 PM</Listing>
<Listing>Feb 24- at  North Florida, 7:00 PM</Listing>
</Team>
<Team fullname="Campbell Fighting Camels">
<Listing>Nov 11-W vs. UNC-Pembroke, 106-66</Listing>
<Listing>Nov 16-W vs. Coastal Carolina, 83-63</Listing>
<Listing>Nov 20-W vs. UNC-Wilmington, 100-94</Listing>
<Listing>Nov 25-L at  Radford, 80-87</Listing>
<Listing>Nov 27-L at  Appalachian St, 71-84</Listing>
<Listing>Dec 12-L at  San Diego St, 82-119</Listing>
<Listing>Dec 14-L at  San Diego, 69-81</Listing>
<Listing>Dec 18-W vs. Radford, 101-88</Listing>
<Listing>Dec 23-L at  Virginia Tech, 70-94</Listing>
<Listing>Dec 30-W vs. Ohio Valley, 107-65</Listing>
<Listing>Jan  2-W at  North Florida, 78-48</Listing>
<Listing>Jan  4-L at  Jacksonville, 71-90</Listing>
<Listing>Jan  6-W vs. Kennesaw St, 88-85 2OT</Listing>
<Listing>Jan  9-L vs. East Tenn St, 76-100</Listing>
<Listing>Jan 13-L at  Mercer, 93-94</Listing>
<Listing>Jan 15-L at  Stetson, 73-82</Listing>
<Listing>Jan 18- vs. Belmont, 7:00 PM</Listing>
<Listing>Jan 20- vs. Lipscomb, 1:00 PM</Listing>
<Listing>Jan 25- vs. North Florida, 8:00 PM</Listing>
<Listing>Jan 27- vs. Jacksonville, 4:00 PM</Listing>
<Listing>Jan 30- at  Gardner-Webb, 7:00 PM</Listing>
<Listing>Feb  2- at  Kennesaw St, 7:30 PM</Listing>
<Listing>Feb  5- at  East Tenn St, 7:00 PM</Listing>
<Listing>Feb  8- vs. Stetson, 7:00 PM</Listing>
<Listing>Feb 10- vs. Mercer, 7:00 PM</Listing>
<Listing>Feb 15- at  Lipscomb, 8:00 PM</Listing>
<Listing>Feb 17- at  Belmont, 7:30 PM</Listing>
<Listing>Feb 22- vs. Longwood, 7:00 PM</Listing>
<Listing>Feb 24- vs. Gardner-Webb, 6:00 PM</Listing>
</Team>
<Team fullname="East Tennessee State Buccaneers">
<Listing>Nov 10-W vs. Virginia-Wise, 90-43</Listing>
<Listing>Nov 13-L at  Eastern Ky, 53-70</Listing>
<Listing>Nov 15-W vs. Chattanooga, 71-70 OT</Listing>
<Listing>Nov 19-L at  Auburn, 58-64</Listing>
<Listing>Nov 21-L at  Morehead State, 56-77</Listing>
<Listing>Nov 24-L vs. Sam Houston St, 61-72</Listing>
<Listing>Nov 25-W at  Southern U, 66-52</Listing>
<Listing>Nov 30-W at  Mercer, 76-70</Listing>
<Listing>Dec  2-W at  Stetson, 75-61</Listing>
<Listing>Dec  5-L at  Vanderbilt, 62-104</Listing>
<Listing>Dec  9-W vs. Milligan, 73-47</Listing>
<Listing>Dec 19-W vs. UNC-Asheville, 73-65</Listing>
<Listing>Dec 21-W vs. Radford, 71-51</Listing>
<Listing>Dec 30-L at  Tennessee, 88-93</Listing>
<Listing>Jan  2-L vs. Belmont, 74-75 OT</Listing>
<Listing>Jan  4-W vs. Lipscomb, 75-72 OT</Listing>
<Listing>Jan  7-W at  Gardner-Webb, 66-63</Listing>
<Listing>Jan  9-W at  Campbell, 100-76</Listing>
<Listing>Jan 13-W vs. North Florida, 77-58</Listing>
<Listing>Jan 15-W vs. Jacksonville, 71-59</Listing>
<Listing>Jan 19- vs. Kennesaw St, 7:30 PM</Listing>
<Listing>Jan 25- at  Belmont, 7:00 PM</Listing>
<Listing>Jan 27- at  Lipscomb, 5:00 PM</Listing>
<Listing>Feb  2- vs. Gardner-Webb, 7:00 PM</Listing>
<Listing>Feb  5- vs. Campbell, 7:00 PM</Listing>
<Listing>Feb  8- at  Jacksonville, 7:00 PM</Listing>
<Listing>Feb 10- at  North Florida, 4:00 PM</Listing>
<Listing>Feb 17- at  Kennesaw St, 7:30 PM</Listing>
<Listing>Feb 23- vs. Stetson, 7:30 PM</Listing>
<Listing>Feb 25- vs. Mercer, 2:00 PM</Listing>
</Team>
<Team fullname="Gardner-Webb Bulldogs">
<Listing>Nov 13-L at  Texas Tech, 74-86</Listing>
<Listing>Nov 14-L vs. Akron, 61-89</Listing>
<Listing>Nov 19-L at  North Carolina, 50-103</Listing>
<Listing>Nov 21-L vs. UNC Greensboro, 67-79</Listing>
<Listing>Nov 24-L at  NC State, 76-88</Listing>
<Listing>Nov 29-W vs. Ferrum, 70-53</Listing>
<Listing>Dec  5-L at  Georgia, 67-96</Listing>
<Listing>Dec  9-W vs. Western Carolina, 74-73 O</Listing>
<Listing>Dec 16-L at  High Point, 51-65</Listing>
<Listing>Dec 19-L at  Wake Forest, 60-92</Listing>
<Listing>Dec 27-L at  Wisconsin, 40-98</Listing>
<Listing>Jan  2-L at  Jacksonville, 64-73</Listing>
<Listing>Jan  4-W at  North Florida, 72-52</Listing>
<Listing>Jan  7-L vs. East Tenn St, 63-66</Listing>
<Listing>Jan 10-L vs. Kennesaw St, 60-77</Listing>
<Listing>Jan 13-W at  Stetson, 77-64</Listing>
<Listing>Jan 15-L at  Mercer, 74-85</Listing>
<Listing>Jan 18- vs. Lipscomb, 7:00 PM</Listing>
<Listing>Jan 20- vs. Belmont, 6:00 PM</Listing>
<Listing>Jan 25- vs. Jacksonville, 6:00 PM</Listing>
<Listing>Jan 27- vs. North Florida, 8:15 PM</Listing>
<Listing>Jan 30- vs. Campbell, 7:00 PM</Listing>
<Listing>Feb  2- at  East Tenn St, 7:00 PM</Listing>
<Listing>Feb  4- at  Kennesaw St, 2:00 PM</Listing>
<Listing>Feb  8- vs. Mercer, 7:00 PM</Listing>
<Listing>Feb 10- vs. Stetson, 7:00 PM</Listing>
<Listing>Feb 15- at  Belmont, 7:00 PM</Listing>
<Listing>Feb 17- at  Lipscomb, 3:00 PM</Listing>
<Listing>Feb 24- at  Campbell, 6:00 PM</Listing>
</Team>
<Team fullname="Jacksonville Dolphins">
<Listing>Nov 12-L at  Savannah State, 64-67</Listing>
<Listing>Nov 14-W vs. Saint Leo, 77-73</Listing>
<Listing>Nov 16-L at  Florida, 61-90</Listing>
<Listing>Nov 22-W vs. Florida Tech, 89-60</Listing>
<Listing>Nov 25-W vs. SC State, 87-74</Listing>
<Listing>Nov 27-L at  U-C-F, 62-99</Listing>
<Listing>Nov 30-L at  Lipscomb, 61-73</Listing>
<Listing>Dec  2-L at  Belmont, 62-76</Listing>
<Listing>Dec 10-W vs. Coastal Carolina, 85-72</Listing>
<Listing>Dec 16-L at  Texas A&amp;M, 58-97</Listing>
<Listing>Dec 19-L at  Georgia, 77-93</Listing>
<Listing>Dec 29-L at  South Carolina, 73-80</Listing>
<Listing>Jan  2-W vs. Gardner-Webb, 73-64</Listing>
<Listing>Jan  4-W vs. Campbell, 90-71</Listing>
<Listing>Jan  9-W at  North Florida, 64-60</Listing>
<Listing>Jan 13-L at  Kennesaw St, 76-83</Listing>
<Listing>Jan 15-L at  East Tenn St, 59-71</Listing>
<Listing>Jan 18- vs. Mercer, 7:00 PM</Listing>
<Listing>Jan 20- vs. Stetson, 7:00 PM</Listing>
<Listing>Jan 25- at  Gardner-Webb, 6:00 PM</Listing>
<Listing>Jan 27- at  Campbell, 4:00 PM</Listing>
<Listing>Feb  3- vs. North Florida, 6:00 PM</Listing>
<Listing>Feb  8- vs. East Tenn St, 7:00 PM</Listing>
<Listing>Feb 10- vs. Kennesaw St, 7:00 PM</Listing>
<Listing>Feb 16- at  Mercer, 7:30 PM</Listing>
<Listing>Feb 18- at  Stetson, 5:00 PM</Listing>
<Listing>Feb 22- vs. Belmont, 6:00 PM</Listing>
<Listing>Feb 24- vs. Lipscomb, 6:00 PM</Listing>
<Listing></Listing>
<Listing></Listing>
<Listing></Listing>
</Team>
<Team fullname="Kennesaw Fighting Owls">
<Listing>Nov 11-L vs. Western Ky, 55-96</Listing>
<Listing>Nov 17-W at  St Peters, 67-60</Listing>
<Listing>Nov 18-L at  Columbia, 51-63</Listing>
<Listing>Nov 21-L vs. George Washington, 52-69</Listing>
<Listing>Nov 25-L vs. Florida Intl, 68-70</Listing>
<Listing>Nov 28-W vs. Newberry, 68-55</Listing>
<Listing>Nov 30-L at  Stetson, 56-61</Listing>
<Listing>Dec  2-L at  Mercer, 77-84 OT</Listing>
<Listing>Dec 17-L at  Kansas State, 54-82</Listing>
<Listing>Dec 19-L at  Wichita State, 65-74</Listing>
<Listing>Dec 22-W at  MD-Eastern Shore, 67-49</Listing>
<Listing>Dec 23-L at  Longwood, 85-87 OT</Listing>
<Listing>Dec 29-L at  Chattanooga, 67-83</Listing>
<Listing>Dec 30-W vs. Alabama State, 78-72</Listing>
<Listing>Jan  2-W vs. Lipscomb, 66-55</Listing>
<Listing>Jan  4-L vs. Belmont, 45-63</Listing>
<Listing>Jan  6-L at  Campbell, 85-88 2OT</Listing>
<Listing>Jan 10-W at  Gardner-Webb, 77-60</Listing>
<Listing>Jan 13-W vs. Jacksonville, 83-76</Listing>
<Listing>Jan 15-W vs. North Florida, 77-57</Listing>
<Listing>Jan 19- at  East Tenn St, 7:30 PM</Listing>
<Listing>Jan 25- at  Lipscomb, 8:00 PM</Listing>
<Listing>Jan 27- at  Belmont, 7:00 PM</Listing>
<Listing>Feb  2- vs. Campbell, 7:30 PM</Listing>
<Listing>Feb  4- vs. Gardner-Webb, 2:00 PM</Listing>
<Listing>Feb  8- at  North Florida, 7:00 PM</Listing>
<Listing>Feb 10- at  Jacksonville, 7:00 PM</Listing>
<Listing>Feb 14- at  Georgia, 7:30 PM</Listing>
<Listing>Feb 17- vs. East Tenn St, 7:30 PM</Listing>
<Listing>Feb 22- vs. Mercer, 7:30 PM</Listing>
<Listing>Feb 24- vs. Stetson, 2:00 PM</Listing>
</Team>
<Team fullname="Lipscomb Bison">
<Listing>Nov 11-W vs. Tusculum, 70-67</Listing>
<Listing>Nov 13-W vs. Evansville, 67-64</Listing>
